global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'bem-production'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Load rules once and periodically evaluate them
rule_files:
  - "alerts.yml"

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter - System metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+).*'

  # cAdvisor - Container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # ECM Gateway metrics
  - job_name: 'ecm-gateway'
    static_configs:
      - targets: ['ecm-gateway:8765']
    metrics_path: '/metrics'

  # AA Service metrics
  - job_name: 'aa-service'
    static_configs:
      - targets: ['bem-aa:8003']
    metrics_path: '/metrics'

  # Microservice engines
  - job_name: 'callback-engine'
    static_configs:
      - targets: ['callback-engine:8004']
    metrics_path: '/metrics'

  - job_name: 'dag-alpha'
    static_configs:
      - targets: ['dag-alpha:8005']
    metrics_path: '/metrics'

  - job_name: 'functor-types'
    static_configs:
      - targets: ['functor-types:8006']
    metrics_path: '/metrics'

  - job_name: 'graph-runtime'
    static_configs:
      - targets: ['graph-runtime:8007']
    metrics_path: '/metrics'

  - job_name: 'optimization'
    static_configs:
      - targets: ['optimization:8008']
    metrics_path: '/metrics'

  # PostgreSQL exporter (if added)
  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Redis exporter (if added)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121'] 