# Render.com Official Deployment Configuration
# BEM System - Git-Powered CI/CD
# Auto-deploys on Git push to main branch

databases:
  - name: bem-db
    databaseName: bem_production
    user: bem_user
    postgresMajorVersion: 15
    ipAllowList:
      - source: 0.0.0.0/0
        description: Allow all connections (use more restrictive in production)

services:
  # Automated Admin (AA) - Behavior Classification Service
  - type: web
    name: bem-aa
    runtime: docker
    dockerfilePath: ./deploy/Dockerfile.behavior-ac
    dockerContext: .
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bem-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: bem-redis
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 8003
    healthCheckPath: /health
    initialDeployHook: |
      echo "Running AA service initialization..."
      python -m neon.database_integration --init-tables
    autoDeploy: true
    
  # ECM Gateway - WebSocket Handler
  - type: web
    name: bem-ecm
    runtime: docker
    dockerfilePath: ./deploy/Dockerfile.ecm
    dockerContext: .
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bem-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: bem-redis
          property: connectionString
      - key: AUDIT_LOG_PATH
        value: /logs/ecm_audit.log
      - key: SSL_CERT_PATH
        value: /certs/cert.pem
      - key: SSL_KEY_PATH
        value: /certs/key.pem
      - key: PORT
        value: 8765
    healthCheckPath: /health
    autoDeploy: true
    
  # Frontend Static Site
  - type: static
    name: bem-frontend
    staticPublishPath: ./frontend
    buildCommand: |
      echo "Building frontend assets..."
      # If using a build tool, add commands here
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: X-XSS-Protection
        value: 1; mode=block
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    autoDeploy: true

# Environment Variables (set in Render dashboard):
# POSTGRES_PASSWORD - Generated automatically
# SECRET_KEY - Generate secure random string
# ALLOWED_HOSTS - Set to your custom domain
# GPU_CLOUD_URL - URL of GPU cloud instance for Unreal Engine
# UNREAL_PIXEL_STREAM_URL - Pixel streaming endpoint

# Custom Domains (configure in Render dashboard):
# - bem-automated-admin.your-domain.com
# - bem-ecm-gateway.your-domain.com  
# - bem-ui.your-domain.com
# - bem-dgl.your-domain.com

# Deployment Flow:
# 1. Git push to main → Triggers Render auto-deploy
# 2. Services build and deploy automatically
# 3. Database migrations run (if configured)
# 4. Health checks verify deployment
# 5. Traffic routes to new version
# 6. Old version terminated

# Scaling Configuration:
# - AA Service: Auto-scale 1-3 instances based on traffic
# - ECM Gateway: Always-on 1-2 instances (persistent WebSocket)
# - Static UI: CDN-cached, unlimited scaling
# - DGL Training: 1 instance (can scale manually for training jobs)

# Cost Breakdown (Monthly):
# - PostgreSQL: $7/month (Starter)
# - AA Service: $7/month (Starter) 
# - ECM Gateway: $25/month (Standard - always-on)
# - Static Site: Free
# - DGL Training: $25/month (Standard)
# Total: $64/month

# Production Scaling (higher plans):
# - PostgreSQL: $20/month (Standard)
# - AA Service: $25/month (Standard)
# - ECM Gateway: $25/month (Standard)  
# - DGL Training: $85/month (Pro - more CPU/memory)
# Total: $155/month

# Redis for Sessions and Rate Limiting
- name: bem-redis
  type: redis
  ipAllowList:
    - source: 0.0.0.0/0
      description: Allow all connections

# Background Jobs (Optional)
jobs:
  # DGL Training Job
  - type: cron
    name: bem-dgl-training
    runtime: docker
    dockerfilePath: ./deploy/Dockerfile.dgl-trainer
    dockerContext: .
    schedule: "0 2 * * *"  # Run at 2 AM daily
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bem-db
          property: connectionString
      - key: MODEL_STORAGE_PATH
        value: /models
      - key: TRAINING_EPOCHS
        value: 50 