services:
  - type: web
    name: cad-parser-api
    env: python
    rootDir: render
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --chdir render server:app
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
      - key: OPENAI_API_KEY
        sync: false
      - key: NEO4J_URI
        sync: false
      - key: NEO4J_USER
        sync: false
      - key: NEO4J_PASSWORD
        sync: false
    healthCheckPath: /health 