services:
  - type: web
    name: cad-parser-api
    env: python
    rootDir: src
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHONPATH
        value: ${PWD}
      - key: PORT
        value: 10000
      - key: FLASK_APP
        value: app.py
      - key: OPENAI_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: cad-parser-db
          property: connectionString
      - key: DB_HOST
        value: ep-white-waterfall-a85g0dgx-pooler.eastus2.azure.neon.tech
      - key: DB_NAME
        value: neondb
      - key: DB_USER
        value: neondb_owner
      - key: DB_PASSWORD
        value: npg_CcgA0kKeYVU2
    healthCheckPath: /health

databases:
  - name: cad-parser-db
    databaseName: cad_parser
    user: cad_parser_user
    plan: free 