services:
  - type: web
    name: cad-parser-api
    env: python
    rootDir: src
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHONPATH
        value: ${PWD}
      - key: PORT
        value: 10000
      - key: FLASK_APP
        value: app.py
      - key: OPENAI_API_KEY
        sync: false
      - key: NEO4J_URI
        sync: false
      - key: NEO4J_USER
        sync: false
      - key: NEO4J_PASSWORD
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: cad-parser-db
          property: connectionString
    healthCheckPath: /health

databases:
  - name: cad-parser-db
    databaseName: cad_parser
    user: cad_parser_user
    plan: free 