version: '3.8'

services:
  ne-dag-alpha:
    build: ./ne-dag-alpha
    volumes:
      - ./inputs:/inputs:ro
      - ./outputs:/outputs
      - ./shared:/shared:ro
      - ./pulse:/pulse:ro
    working_dir: /app

#  ne-functor-types:
#    build: ./ne-functor-types
#    volumes:
#      - ./inputs:/inputs:ro
#      - ./outputs:/outputs
#      - ./shared:/shared:ro
#      - ./pulse:/pulse:ro
#    working_dir: /app

#  ne-callback-engine:
#    build: ./ne-callback-engine
#    volumes:
#      - ./inputs:/inputs:ro
#      - ./outputs:/outputs
#      - ./shared:/shared:ro
#      - ./pulse:/pulse:ro
#    working_dir: /app

#  sfde:
#    build: ./sfde
#    volumes:
#      - ./inputs:/inputs:ro
#      - ./outputs:/outputs
#      - ./shared:/shared:ro
#      - ./pulse:/pulse:ro
#    working_dir: /app

  ne-graph-runtime-engine:
    build: ./ne-graph-runtime-engine
    volumes:
      - ./inputs:/inputs:ro
      - ./outputs:/outputs
    working_dir: /app
    command: python main.py 